/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("homework.tds.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
}

application {
    // Define the main class for the application.
    mainClass.set("homework.tds.MainKt")
}
